### ISSUE TITLE
Use model to predict number of bikes at station

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#10]
Once we've [picked a statistical model](https://github.com/dssg/bikeshare/issues/7) and [estimated its parameters](https://github.com/dssg/bikeshare/issues/8), we need to use this model to actually predict how many bikes are going to be at every station in a bikeshare system in 60 minutes.

So we need a `ARMA_prediction.py` script that
1. Defines the [ARMA model](http://en.wikipedia.org/wiki/Autoregressive%E2%80%93moving-average_model) we're using.
2. Takes the parameter estimates output by `parameter_estimation.py` and uses them for our model
3. Query the database to get the current number of bikes at the station, time, day of week, month, and whatever other inputs the model needs.
4. Throw these inputs into the model and spit out a prediction of the number of bikes that will be present at each station in 60 minutes. This predicted output will eventually be shown on a [simple webpage](http://divvybikes.com/stations/json).

**Comment by jpvelez** [comment]
@fishmanadam, @breannam, and @ejette are on this.

**Comment by ejette** [comment]
Right now, this functionality is included in the <a href="https://github.com/dssg/bikeshare/blob/master/basic_stats/Model%20Validation.py">model validation script</a> to compare our predictions to known values.  Once the validation script is complete and we have chose a model, we can write a separate prediction scrip.

**Comment by jpvelez** [comment]
Awesome! Please name or link to the validation script =)

**Comment by ejette** [comment]
sorry! still getting the hang of this issue business :)

On Wed, Jul 17, 2013 at 12:29 PM, Juan-Pablo Velez <notifications@github.com

**Comment by hunterowens** [comment]
Closing because we need a lot of models. See the `models` directory for more info.
