### ISSUE TITLE
Make stupid simple web app to show model results

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#11]
Here are the fields we want to show in a table on a page:
- station name
- percent full right now
- how long station has been full/empty as of now
- % full one hour from now
- how long will it have been full/empty in 60 minutes

**Comment by jpvelez** [comment]
We can do this with flask + bootstrap.

**Comment by nathanleiby** [comment]
Again, this sounds pretty similar to what Banana-bike does already using Flask + PyMongo + Chart.js. Of course could be more elegantly presented.

We show
- YES - Station name
- SORT OF - % full -> almost there: shows Bikes present / Empty spots present
- SORT OF - how long station has been full/empty - we show Info for the past 1 hour but could easily do more
- NO % full one hour from now
- NO how long will it have been full/empty in 60 minutes

see live app: http://rocky-brook-6198.herokuapp.com/station/23

other links are of the form: http://rocky-brook-6198.herokuapp.com/station/<station_id>, where the ids of stations can be found here: https://github.com/nathanleiby/banana-bike/blob/master/server.py

**Comment by hunterowens** [comment]
Closing thank's to the branch from @darkzeroman
