### ISSUE TITLE
Write scraper to get current bike availability data into the database

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#12]
An important input into our [prediction script](https://github.com/dssg/bikeshare/issues/10) is the current number of bikes at each station.

Currently we only have historical bike availability data in the database. So we need to write a scraper that hits the API for DC and adds current station status to the database.

**Comment by jpvelez** [comment]
Before doing going off and doing this, let's make sure there's no open source project that already does it. Here are some candidates:
- [Pybikes](https://github.com/eskerda/PyBikes) - for all stations
- [CapitalBikeshareAPI](https://github.com/MiniCodeMonkey/Capital-Bikeshare-API) - for DC
- [divvy_bikes_api](https://github.com/abeinstein/divvy_bikes_python/blob/master/divvy_data.py) - for Chicago
- @gabegaster is also working on a scraper for Chicago

**Comment by nathanleiby** [comment]
i have one already, made by abe gong when he visited. (and slightly
modified to store into MongoDb)

to be run infinitely (while loop + sleep)
https://github.com/nathanleiby/banana-bike/blob/master/scripts/divvy_grabber.py

to be run as a cron job
https://github.com/nathanleiby/banana-bike/blob/master/scripts/divvy_grabber_cron.py

this works with the json version of the API that is used in Chicago.

**Comment by hunterowens** [comment]
Washington DC, Minneapolis and Boston now live updating on the _ind_ tables. Waiting for Oliver to give math for **agg** before doing those. 

Moving on to NYC/Chicago JSON APIs.

**Comment by hunterowens** [comment]
- [x] XML API script for _ind_ tables for the V1 of the api. (XML) 
- [x] JSON API script for _ind tables for the V2 of the api. (JSON)
- [ ] XML API script for _agg_ tables for the V1 of the api. (XML)
- [ ] JSON API script for _agg_ tables for the V2 of the api. (JSON)

**Comment by hunterowens** [comment]
Waiting on Oliver O'Brian to get back to us about how he generates the `__agg__`  tables. Otherwise done. #9 Also.

**Comment by hunterowens** [comment]
Finished. Opening issue on Agg tables.
