### ISSUE TITLE
Write model validation script

### ISSUE THREAD

**Issue by ejette** [dssg/bikeshare#14]
This involves figuring out the best way to use some data as a test set. For example, do we randomly leave out data points and subsequent data points (based on the "degree" of the AR model we're using), train the model, and then see how we did on our left out points?

**Comment by breannam** [comment]
See the last section of this <a href="http://robjhyndman.com/hyndsight/crossvalidation/">reference for cross-validation</a>, about time series

**Comment by ejette** [comment]
We've started the validation script (Model Validation.py). Closing this issue because we have created more detailed issues labeled "model validation" that will help us complete this task.
