### ISSUE TITLE
Change alpha parameter from linear to time-varying

### ISSUE THREAD

**Issue by breannam** [dssg/bikeshare#32]

**Comment by breannam** [comment]
Making progress: currently have 3 different alphas for 3 time buckets- one for morning (midnight to 8am), one for midday (8am-4pm), one for evening (4pm-midnight).  Working to generalize to allow number of time buckets to be selected before closing issue

**Comment by jpvelez** [comment]
@ejette @breannam close this one too? If so, please state why for the historical record. =)

**Comment by ejette** [comment]
Binomial model no longer exists. Time-varying alpha unnecessary.
