### ISSUE TITLE
Provide historical data on S3 so people can get it. 

### ISSUE THREAD

**Issue by hunterowens** [dssg/bikeshare#40]

**Comment by HarlanH** [comment]
Hello! I tried to email you guys via your google group, but it's not set up to post messages from non-subscribers, so mentioning here.

I'm working with a team at Code for DC (the local chapter of Code for America). We independently decided we wanted to build a statistical model very similar what you're working on, and ran across your project! 

Would you be willing to share your data set with us, so we don't have to start scraping from scratch? Is there anything we can do to get this issue moving?

(The thing that we're currently interested is the commuter issue -- for each station, when is the dock likely to become empty/full in the morning/evening? Big problem, in practice!)

Thanks!

**Comment by hunterowens** [comment]
@HarlanH Sorry about the delay, I've been meaning to get this setup, but for now, do you have a postgres install ready and configed to handle the dataset? I've started a pg_dump that I'll put on S3 once you are ready to receive it (it's north of 100gb, south of 1tb last time I checked the size of the database.)

**Comment by HarlanH** [comment]
Wow, that's pretty good. How many records do you have? Tens of millions? If
you're pushing it to S3, would it make sense to make a view of the data
available on Redshift? That might make sense...

**Comment by hunterowens** [comment]
Around 120 million~ (and counting) in the case of DC. A m1.large
instance+1TB drive has given us pretty good performance so far, especially
with indexing.

**Comment by HarlanH** [comment]
Hm, OK. We can do that. In theory, it'd be maybe better to export this in something other than Postgres, but beggars, choosers, and all that. :)

**Comment by hunterowens** [comment]
I could also do a CSV dump, I believe. That work better for your setup?

**Comment by HarlanH** [comment]
It'd be more flexible, certainly! For both us and others, daily CSV files
would give us the most options, from loading into arbitrary databases
(Redshift would be fun), to direct processing one file at a time. I wonder
what would be an easy, cost-effective options for you guys on an ongoing
basis?

**Comment by hunterowens** [comment]
Harlan-

I'm thinking the best, long term solution is to provide a API that will
allow users to get the data they need in JSON format. I'm going to try and
take a thack at that sometime soon.

Short term, what works best so the CFA DC team can get working?

Thanks,
Hunter

**Comment by HarlanH** [comment]
Hunter, yes, an API would be great. (It'd be even better if CaBi ran their
own API, but whatever.)

Short term, would you be willing to just run a SQL query and dump to a CSV
file? We'd like all DC stations, but we only need snapshots every 10
minutes (I'm guessing you're pulling every minute) from say 6am to 10am,
for maybe the last 6 months. I'm not sure what columns are available...

Thanks!

**Comment by hunterowens** [comment]
@HarlanH - Sorry for the delay, been away from a decent internet connection for a while. 

I gave you the entire dataset - from roughly system going online to today. Due to bugs in the collecting process, some observations are missing. Originally, [Oliver O'Brien](http://www.oobrien.com/) was collecting data at 2 minute intervals, which has now been replaced with 1 minute intervals. The data documentation is the wiki/README is pretty good, but feel free to ask questions. FYI, you're looking at the `bike_ind_washingtondc` table for reference. 

[Raw](https://s3-us-west-2.amazonaws.com/dssg-bikeshare/washingtondc.csv) 3.5 GB on S3 
[Gzip](https://s3-us-west-2.amazonaws.com/dssg-bikeshare/washingtondc.csv.gz) ~500 MB.

**Comment by hunterowens** [comment]
@HarlanH Also, if anybody in your group is interested in building an API, let me know.

**Comment by HarlanH** [comment]
Just a note to thank you for sending this data! I've extracted a
model-friendly summary, which is on the Code for DC CKAN site:
http://opendatadc.org/dataset/capital-bikeshare-first-empty-time We'll be
working on building some models and visualizations around this soon!

**Comment by hunterowens** [comment]
Closing this issue. See #68 for more info.

**Comment by erinselene** [comment]
I have been using this washingtondc csv you posted and building off your code. However, I'm wondering if the timezone conversion that's in your code already has been done here, since it's not lining up with some overlapping data I got from Alta (Yours appears as 5 hours earlier). Do you happen to know? Thank you.
