### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by hunterowens** [dssg/bikeshare#42]
## REQUIRED WIKI SECTIONS
- [x] Homepage
  
  > Intro: have a sentence or two about the project: the problems its solving, the partner, and how you're solving it. Also say that "this wiki is the central place to learn about the social problem we worked on, the data we used, the methods we used to solve it, and our findings" so people know what they're looking at.
  > List of pages in the wiki
- [x] Problem
  
  > An in-depth description of the problem your organization, the problem you're trying to solve, and any relevant domain knowledge. Feel free to copy from blog posts and posters, if relevant.
- [x] Data
  
  > Describe the dataset(s) you used in the project as well as your database. Walk people through the data model (tables are handy for this), and include a (fake) sample of each dataset.
  > If you scraped data, this is the place to document that.
- [ ] Methodology
  
  > An in-depth, technical write up of the method(s) you used on your projects. Use latex equation, walk people through algorithms and models, link out to relevant documentation when possible.
- [x] Results
  
  > Discuss what metrics you're using to evaluate performance (if applicable), and what your final findings where.
- [ ] Future work
  
  > Discuss what you would like to do / what is in progress. 
## OPTIONAL WIKI SECTIONS - if its fits your project
- [ ] Analysis
  
  >  If you did exploratory data analysis, this is the place to put it and explain your findings. Explain each finding and what your learned from it / how it motivated the methods you used. Put this between the "Data" and "Methodology" sections. Feel free to lift content from relevant blog posts, if any.
- [ ] Resources 
  
  >  Resources for domain knowledge, methods, and tech. Whatever pieces of paper you used to learn what you know.
- [ ] Tool
  - [ ] API Documentation
  - [ ] Web app Documenation

**Comment by hunterowens** [comment]
@darkzeroman is doing the webapp section
@fishmanadam is doing the analysis section

Otherwise, closable.

**Comment by hunterowens** [comment]
Good.

**Comment by joyrexus** [comment]
FWIW, the wiki's [home page](https://github.com/dssg/bikeshare/wiki) section links were not working (see [previous rev](https://github.com/dssg/bikeshare/wiki/Home/7ea8bc7a447dd1b9c0d974dd207a5196251fd118)), but were instead being redirected back to the home page.  This is [a known issue](http://stackoverflow.com/a/8972756/546630) and I [fixed](https://github.com/dssg/bikeshare/wiki/_compare/7ea8bc7a447dd1b9c0d974dd207a5196251fd118...3ac0423e84de3f91169d7e8c9e1e7fb7f8ed6f34) it by replacing the markdown link syntax with MediaWiki link syntax: `[[LINK TEXT|PAGE NAME]]`.

**Comment by hunterowens** [comment]
Thanks, @joyrexus. Didn't know you could fix that with the mediawiki syntax.
