### ISSUE TITLE
Write cron job to run estimation script every day

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#51]

**Comment by hunterowens** [comment]
I need to still do this. Waiting on a final poisson model function to run daily.

**Comment by nathanleiby** [comment]
pretty sure you guys know how to do this, but ...

command line: `crontab -e`

add to the file: 

`59 23 * * * path/to/executable`

**Comment by jpvelez** [comment]
@hunterowens status?

**Comment by hunterowens** [comment]
This script is `web/predicitions.py`? If so done.

**Comment by hunterowens** [comment]
Done.
