### ISSUE TITLE
Finish improving binomial model

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#52]

**Comment by hunterowens** [comment]
Issue #32 is part of this.

**Comment by wdempsey** [comment]
On hold for now.

**Comment by jpvelez** [comment]
@ejette and @breannam, are you guys going to try to get this working, with [time-varying alphas](https://github.com/dssg/bikeshare/issues/32)?

If so, awesome! If not, please close this issue and make relevant changes to the codebase (delete binomial stuff, or stash it in a separate folder with good documentation that explains where things stand.)

**Comment by ejette** [comment]
Will check in with @breannam about this. She is driving across the country today so probably won't be able to talk.

**Comment by ejette** [comment]
Oops. Did not mean to close just yet.
