### ISSUE TITLE
DC app map tiles not displaying

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#63]
The base map tiles from Mapbox in the DC app aren't always displaying because the account they're being pulled from is a trial account and has run out of monthly views.

We need to the map to an account with more views, and point the app to that new API.

**Comment by hunterowens** [comment]
I think we need to change 

```
  // Made TileMap with JSON with Vidhur's account
  // darkzeroman.map-gxrlhgnw : NYC MAP
  MYAPP.map = L.mapbox.map('map', 'darkzeroman.map-bi97back').whenReady(function () {
```

in `bikeshare/web/static/javascript/custom_mapbox.js`
