### ISSUE TITLE
Figure out the terms of the ARMA model we're using

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#7]
We're using an ARMA statistical model to predict the number of bikes and docks available at a station at a certain time. 

They can be more or less complicated, so let's figure out what terms we want in the first, simple version. We can also do something more complicated, but let's start simple.

**Comment by jpvelez** [comment]
@fishmanadam, @breannam, and @ejette are on this.

**Comment by jpvelez** [comment]
Make sure to document the model in the wiki!

**Comment by hunterowens** [comment]
Reminder about fault tolerance. See  #8

**Comment by hunterowens** [comment]
Model implemented.
