### ISSUE TITLE
Show Chicago examples instead of D.C. 

### ISSUE THREAD

**Issue by stevevance** [dssg/bikeshare#70]
Is there enough data to apply the analysis to Chicago?

**Comment by hunterowens** [comment]
I would bet that we would need a full year, so not enough data yet - closing. Give me trip data though.

**Comment by joyrexus** [comment]
Could this issue be re-opened? As you probably know, Divvy is now providing [Chicago trip data for all of 2013](https://divvybikes.com/assets/images/Divvy_Stations_Trips_2013.zip) as part of the [Divvy Data Challenge](https://divvybikes.com/datachallenge).

## The Divvy Dataset

Consists of trip data for the 750,000 trips taken in 2013. Each trip is anonymized and includes:
- Trip start day and time
- Trip end day and time
- Trip start station
- Trip end station
- Rider type (Member or 24-Hour Pass User)
- If a Member trip, it will also include Member’s gender and year of birth

---

As noted on [this recent blog post](http://dssg.io/2014/01/23/divvy-crystal-ball-rebalancing.html):

> If we had each bike’s daily trip data – the set of stations it departed from and arrived to (stripped of personal customer information, of course) – we could model the system holistically rather than treating each station as an island.
