### ISSUE TITLE
Estimate model parameters

### ISSUE THREAD

**Issue by jpvelez** [dssg/bikeshare#8]
Once we have [the model](https://github.com/dssg/bikeshare/issues/7) we want, we need to estimate its parameters by crunching historical data of number of bikes and docks at each station.

So we need a `parameter_estimation.py` script that:
1. Pulls all the historical data we need to do that estimation from the database using SQL query and puts it in a dataframe.
2. Estimates the parameters using this dataframe
3. Spits out the parameters as a vector so our model can use them in our prediction script.

**Comment by jpvelez** [comment]
@fishmanadam, @breannam, and @ejette are on this.

**Comment by hunterowens** [comment]
Reminder, the model needs to be fault tolerant- ie, there may be missing data at any point.
